services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        command: [ "./wait-for-it.sh", "db:5432", "--", "php-fpm" ]
        environment:
            - DATABASE_URL=pgsql://user:userpassword@db:5432/order_db
        volumes:
            - .:/var/www
        working_dir: /var/www
        networks:
            - app-network
        depends_on:
            - db
        entrypoint: [ "./docker/docker-entrypoint.sh" ]

    webserver:
        image: nginx:latest
        container_name: nginx
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_DB: order_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: userpassword
        ports:
            - "5432:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
