services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        command: [ "./wait-for-it.sh", "db:3306", "--", "php-fpm" ]
        volumes:
            - .:/var/www
        working_dir: /var/www
        networks:
            - app-network
        depends_on:
            - db

    webserver:
        image: nginx:latest
        container_name: nginx
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: order_db
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        ports:
            - "3306:3306"
        networks:
            - app-network

    playground:
        image: mpwsh/graphql-playground:latest
        ports:
            - "4000:4000"
        environment:
            - GRAPHQL_ENDPOINT=http://app:8080/graphql  # Update if your endpoint differs
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
