#schema: http://localhost:8080/graphql
schema: schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    default:
      url: http://localhost:8080/graphql
      headers:
        Authorization: Bearer YOUR_TOKEN  # Optional, if you need auth
      introspect: true  # Allows for introspection of the schema
